// House Representatives data from OSINT feeds
export interface HouseMember {
  name: string
  chamber: "House"
  party: "Republican" | "Democrat"
  state: string
  district: string
  officialHandle: string
}

export const HOUSE_MEMBERS: HouseMember[] = [
  // Alaska
  {
    name: "Nick Begich",
    chamber: "House",
    party: "Republican",
    state: "AK",
    district: "At-Large",
    officialHandle: "RepNickBegich",
  },

  // Alabama
  {
    name: "Barry Moore",
    chamber: "House",
    party: "Republican",
    state: "AL",
    district: "1",
    officialHandle: "RepBarryMoore",
  },
  {
    name: "Shomari Figures",
    chamber: "House",
    party: "Democrat",
    state: "AL",
    district: "2",
    officialHandle: "ShomariFigures",
  },
  {
    name: "Mike Rogers",
    chamber: "House",
    party: "Republican",
    state: "AL",
    district: "3",
    officialHandle: "RepMikeRogersAL",
  },
  {
    name: "Robert Aderholt",
    chamber: "House",
    party: "Republican",
    state: "AL",
    district: "4",
    officialHandle: "Robert_Aderholt",
  },
  {
    name: "Dale Strong",
    chamber: "House",
    party: "Republican",
    state: "AL",
    district: "5",
    officialHandle: "RepDaleStrong",
  },
  {
    name: "Gary Palmer",
    chamber: "House",
    party: "Republican",
    state: "AL",
    district: "6",
    officialHandle: "USRepGaryPalmer",
  },
  {
    name: "Terri Sewell",
    chamber: "House",
    party: "Democrat",
    state: "AL",
    district: "7",
    officialHandle: "RepTerriSewell",
  },

  // Arkansas
  {
    name: "Rick Crawford",
    chamber: "House",
    party: "Republican",
    state: "AR",
    district: "1",
    officialHandle: "RepRickCrawford",
  },
  {
    name: "French Hill",
    chamber: "House",
    party: "Republican",
    state: "AR",
    district: "2",
    officialHandle: "RepFrenchHill",
  },
  {
    name: "Steve Womack",
    chamber: "House",
    party: "Republican",
    state: "AR",
    district: "3",
    officialHandle: "Rep_SteveWomack",
  },
  {
    name: "Bruce Westerman",
    chamber: "House",
    party: "Republican",
    state: "AR",
    district: "4",
    officialHandle: "RepWesterman",
  },

  // Arizona
  {
    name: "David Schweikert",
    chamber: "House",
    party: "Republican",
    state: "AZ",
    district: "1",
    officialHandle: "RepDavid",
  },
  {
    name: "Eli Crane",
    chamber: "House",
    party: "Republican",
    state: "AZ",
    district: "2",
    officialHandle: "RepEliCrane",
  },
  {
    name: "Yassamin Ansari",
    chamber: "House",
    party: "Democrat",
    state: "AZ",
    district: "3",
    officialHandle: "RepYassAnsari",
  },
  {
    name: "Greg Stanton",
    chamber: "House",
    party: "Democrat",
    state: "AZ",
    district: "4",
    officialHandle: "gregstantonaz",
  },
  {
    name: "Andy Biggs",
    chamber: "House",
    party: "Republican",
    state: "AZ",
    district: "5",
    officialHandle: "RepAndyBiggsAZ",
  },
  {
    name: "Juan Ciscomani",
    chamber: "House",
    party: "Republican",
    state: "AZ",
    district: "6",
    officialHandle: "JuanCiscomani",
  },
  {
    name: "Raúl Grijalva",
    chamber: "House",
    party: "Democrat",
    state: "AZ",
    district: "7",
    officialHandle: "RepRaulGrijalva",
  },
  {
    name: "Abraham Hamadeh",
    chamber: "House",
    party: "Republican",
    state: "AZ",
    district: "8",
    officialHandle: "AbrahamHamadeh",
  },
  { name: "Paul Gosar", chamber: "House", party: "Republican", state: "AZ", district: "9", officialHandle: "RepGosar" },

  // California
  {
    name: "Doug LaMalfa",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "1",
    officialHandle: "RepLaMalfa",
  },
  {
    name: "Jared Huffman",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "2",
    officialHandle: "RepHuffman",
  },
  {
    name: "Kevin Kiley",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "3",
    officialHandle: "KevinKileyCA",
  },
  {
    name: "Mike Thompson",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "4",
    officialHandle: "RepThompson",
  },
  {
    name: "Tom McClintock",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "5",
    officialHandle: "RepMcClintock",
  },
  { name: "Ami Bera", chamber: "House", party: "Democrat", state: "CA", district: "6", officialHandle: "RepBera" },
  {
    name: "Doris Matsui",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "7",
    officialHandle: "DorisMatsui",
  },
  {
    name: "John Garamendi",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "8",
    officialHandle: "RepGaramendi",
  },
  {
    name: "Josh Harder",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "9",
    officialHandle: "joshua_harder",
  },
  {
    name: "Mark DeSaulnier",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "10",
    officialHandle: "RepDeSaulnier",
  },
  {
    name: "Nancy Pelosi",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "11",
    officialHandle: "NancyPelosi",
  },
  {
    name: "Lateefah Simon",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "12",
    officialHandle: "RepLSimon",
  },
  {
    name: "Adam Gray",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "13",
    officialHandle: "RepAdamGrayCA",
  },
  {
    name: "Eric Swalwell",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "14",
    officialHandle: "RepSwalwell",
  },
  {
    name: "Kevin Mullin",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "15",
    officialHandle: "kevinmullin",
  },
  {
    name: "Sam Liccardo",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "16",
    officialHandle: "RepLiccardo",
  },
  {
    name: "Ro Khanna",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "17",
    officialHandle: "RepRoKhanna",
  },
  {
    name: "Zoe Lofgren",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "18",
    officialHandle: "RepZoeLofgren",
  },
  {
    name: "Jimmy Panetta",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "19",
    officialHandle: "RepJimmyPanetta",
  },
  {
    name: "Vince Fong",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "20",
    officialHandle: "RepVinceFong",
  },
  {
    name: "Jim Costa",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "21",
    officialHandle: "RepJimCosta",
  },
  {
    name: "David Valadao",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "22",
    officialHandle: "RepDavidValadao",
  },
  {
    name: "Jay Obernolte",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "23",
    officialHandle: "JayObernolte",
  },
  {
    name: "Salud Carbajal",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "24",
    officialHandle: "RepCarbajal",
  },
  {
    name: "Raul Ruiz",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "25",
    officialHandle: "CongressmanRuiz",
  },
  {
    name: "Julia Brownley",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "26",
    officialHandle: "JuliaBrownley26",
  },
  {
    name: "George Whitesides",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "27",
    officialHandle: "Rep_Whitesides",
  },
  { name: "Judy Chu", chamber: "House", party: "Democrat", state: "CA", district: "28", officialHandle: "RepJudyChu" },
  {
    name: "Luz Rivas",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "29",
    officialHandle: "RepLuzRivas",
  },
  {
    name: "Laura Friedman",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "30",
    officialHandle: "RepFriedmanCA",
  },
  {
    name: "Gil Cisneros",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "31",
    officialHandle: "gilcisnerosca",
  },
  {
    name: "Brad Sherman",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "32",
    officialHandle: "BradSherman",
  },
  {
    name: "Pete Aguilar",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "33",
    officialHandle: "RepPeteAguilar",
  },
  {
    name: "Jimmy Gomez",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "34",
    officialHandle: "RepJimmyGomez",
  },
  {
    name: "Norma Torres",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "35",
    officialHandle: "NormaJTorres",
  },
  { name: "Ted Lieu", chamber: "House", party: "Democrat", state: "CA", district: "36", officialHandle: "RepTedLieu" },
  {
    name: "Sydney Kamlager-Dove",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "37",
    officialHandle: "sydneykamlager",
  },
  {
    name: "Linda Sánchez",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "38",
    officialHandle: "RepLindaSanchez",
  },
  {
    name: "Mark Takano",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "39",
    officialHandle: "RepMarkTakano",
  },
  {
    name: "Young Kim",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "40",
    officialHandle: "RepYoungKim",
  },
  {
    name: "Ken Calvert",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "41",
    officialHandle: "KenCalvert",
  },
  {
    name: "Robert Garcia",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "42",
    officialHandle: "RobertGarcia",
  },
  {
    name: "Maxine Waters",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "43",
    officialHandle: "MaxineWaters",
  },
  {
    name: "Nanette Barragán",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "44",
    officialHandle: "RepBarragan",
  },
  {
    name: "Derek Tran",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "45",
    officialHandle: "RepDerekTranCA",
  },
  {
    name: "Lou Correa",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "46",
    officialHandle: "RepLouCorrea",
  },
  { name: "Dave Min", chamber: "House", party: "Democrat", state: "CA", district: "47", officialHandle: "DaveMinCA" },
  {
    name: "Darrell Issa",
    chamber: "House",
    party: "Republican",
    state: "CA",
    district: "48",
    officialHandle: "repdarrellissa",
  },
  {
    name: "Mike Levin",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "49",
    officialHandle: "RepMikeLevin",
  },
  {
    name: "Scott Peters",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "50",
    officialHandle: "RepScottPeters",
  },
  {
    name: "Sara Jacobs",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "51",
    officialHandle: "RepSaraJacobs",
  },
  {
    name: "Juan Vargas",
    chamber: "House",
    party: "Democrat",
    state: "CA",
    district: "52",
    officialHandle: "RepJuanVargas",
  },

  // Colorado
  {
    name: "Diana DeGette",
    chamber: "House",
    party: "Democrat",
    state: "CO",
    district: "1",
    officialHandle: "RepDianaDeGette",
  },
  {
    name: "Joe Neguse",
    chamber: "House",
    party: "Democrat",
    state: "CO",
    district: "2",
    officialHandle: "RepJoeNeguse",
  },
  {
    name: "Jeff Hurd",
    chamber: "House",
    party: "Republican",
    state: "CO",
    district: "3",
    officialHandle: "RepJeffHurd",
  },
  {
    name: "Lauren Boebert",
    chamber: "House",
    party: "Republican",
    state: "CO",
    district: "4",
    officialHandle: "RepBoebert",
  },
  {
    name: "Jeff Crank",
    chamber: "House",
    party: "Republican",
    state: "CO",
    district: "5",
    officialHandle: "RepJeffCrank",
  },
  {
    name: "Jason Crow",
    chamber: "House",
    party: "Democrat",
    state: "CO",
    district: "6",
    officialHandle: "RepJasonCrow",
  },
  {
    name: "Brittany Pettersen",
    chamber: "House",
    party: "Democrat",
    state: "CO",
    district: "7",
    officialHandle: "pettersen4co",
  },
  {
    name: "Gabe Evans",
    chamber: "House",
    party: "Republican",
    state: "CO",
    district: "8",
    officialHandle: "repgabeevans",
  },

  // Connecticut
  {
    name: "John Larson",
    chamber: "House",
    party: "Democrat",
    state: "CT",
    district: "1",
    officialHandle: "RepJohnLarson",
  },
  {
    name: "Joe Courtney",
    chamber: "House",
    party: "Democrat",
    state: "CT",
    district: "2",
    officialHandle: "RepJoeCourtney",
  },
  {
    name: "Rosa DeLauro",
    chamber: "House",
    party: "Democrat",
    state: "CT",
    district: "3",
    officialHandle: "RosaDeLauro",
  },
  { name: "Jim Himes", chamber: "House", party: "Democrat", state: "CT", district: "4", officialHandle: "jahimes" },
  {
    name: "Jahana Hayes",
    chamber: "House",
    party: "Democrat",
    state: "CT",
    district: "5",
    officialHandle: "RepJahanaHayes",
  },

  // Delaware
  {
    name: "Sarah McBride",
    chamber: "House",
    party: "Democrat",
    state: "DE",
    district: "At-Large",
    officialHandle: "Rep_McBride",
  },

  // Florida
  {
    name: "Jimmy Pastronis",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "1",
    officialHandle: "PatronisFL",
  },
  {
    name: "Neal Dunn",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "2",
    officialHandle: "DrNealDunnFL2",
  },
  {
    name: "Kat Cammack",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "3",
    officialHandle: "RepKatCammack",
  },
  {
    name: "Aaron Bean",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "4",
    officialHandle: "RepAaronBean",
  },
  {
    name: "John Rutherford",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "5",
    officialHandle: "RepRutherfordFL",
  },
  {
    name: "Michael Waltz",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "6",
    officialHandle: "RepWaltzPress",
  },
  {
    name: "Cory Mills",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "7",
    officialHandle: "RepMillsPress",
  },
  {
    name: "Mike Haridopolos",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "8",
    officialHandle: "RepHaridopolos",
  },
  {
    name: "Darren Soto",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "9",
    officialHandle: "RepDarrenSoto",
  },
  {
    name: "Maxwell Frost",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "10",
    officialHandle: "MaxwellFrostFL",
  },
  {
    name: "Dan Webster",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "11",
    officialHandle: "RepWebster",
  },
  {
    name: "Gus Bilirakis",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "12",
    officialHandle: "RepGusBilirakis",
  },
  {
    name: "Anna Paulina Luna",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "13",
    officialHandle: "RepLuna",
  },
  {
    name: "Kathy Castor",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "14",
    officialHandle: "USRepKCastor",
  },
  {
    name: "Laurel Lee",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "15",
    officialHandle: "RepLaurelLee",
  },
  {
    name: "Vern Buchanan",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "16",
    officialHandle: "VernBuchanan",
  },
  {
    name: "Greg Steube",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "17",
    officialHandle: "RepGregSteube",
  },
  {
    name: "Scott Franklin",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "18",
    officialHandle: "RepFranklin",
  },
  {
    name: "Byron Donalds",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "19",
    officialHandle: "RepDonaldsPress",
  },
  {
    name: "Sheila Cherfilus-McCormick",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "20",
    officialHandle: "CongresswomanSC",
  },
  {
    name: "Brian Mast",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "21",
    officialHandle: "repbrianmast",
  },
  {
    name: "Lois Frankel",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "22",
    officialHandle: "RepLoisFrankel",
  },
  {
    name: "Jared Moskowitz",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "23",
    officialHandle: "JaredEMoskowitz",
  },
  {
    name: "Frederica Wilson",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "24",
    officialHandle: "RepWilson",
  },
  {
    name: "Debbie Wasserman Schultz",
    chamber: "House",
    party: "Democrat",
    state: "FL",
    district: "25",
    officialHandle: "RepDWStweets",
  },
  {
    name: "Mario Díaz-Balart",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "26",
    officialHandle: "MarioDB",
  },
  {
    name: "Maria Elvira Salazar",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "27",
    officialHandle: "RepMariaSalazar",
  },
  {
    name: "Carlos Giménez",
    chamber: "House",
    party: "Republican",
    state: "FL",
    district: "28",
    officialHandle: "RepCarlos",
  },

  // Georgia
  {
    name: "Buddy Carter",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "1",
    officialHandle: "RepBuddyCarter",
  },
  {
    name: "Sanford Bishop",
    chamber: "House",
    party: "Democrat",
    state: "GA",
    district: "2",
    officialHandle: "SanfordBishop",
  },
  {
    name: "Brian K. Jack",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "3",
    officialHandle: "RepBrianJack",
  },
  {
    name: "Hank Johnson",
    chamber: "House",
    party: "Democrat",
    state: "GA",
    district: "4",
    officialHandle: "RepHankJohnson",
  },
  {
    name: "Nikema Williams",
    chamber: "House",
    party: "Democrat",
    state: "GA",
    district: "5",
    officialHandle: "RepNikema",
  },
  {
    name: "Rich McCormick",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "6",
    officialHandle: "RepMcCormick",
  },
  {
    name: "Lucy McBath",
    chamber: "House",
    party: "Democrat",
    state: "GA",
    district: "7",
    officialHandle: "RepLucyMcBath",
  },
  {
    name: "Austin Scott",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "8",
    officialHandle: "AustinScottGA08",
  },
  {
    name: "Andrew Clyde",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "9",
    officialHandle: "Rep_Clyde",
  },
  {
    name: "Mike Collins",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "10",
    officialHandle: "MikeCollinsGA",
  },
  {
    name: "Barry Loudermilk",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "11",
    officialHandle: "RepLoudermilk",
  },
  {
    name: "Rick Allen",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "12",
    officialHandle: "reprickallen",
  },
  {
    name: "David Scott",
    chamber: "House",
    party: "Democrat",
    state: "GA",
    district: "13",
    officialHandle: "RepDavidScott",
  },
  {
    name: "Marjorie Taylor Greene",
    chamber: "House",
    party: "Republican",
    state: "GA",
    district: "14",
    officialHandle: "RepMTG",
  },

  // Hawaii
  { name: "Ed Case", chamber: "House", party: "Democrat", state: "HI", district: "1", officialHandle: "repedcase" },
  {
    name: "Jill Tokuda",
    chamber: "House",
    party: "Democrat",
    state: "HI",
    district: "2",
    officialHandle: "RepJillTokuda",
  },

  // Iowa
  {
    name: "Mariannette Miller-Meeks",
    chamber: "House",
    party: "Republican",
    state: "IA",
    district: "1",
    officialHandle: "RepMMM",
  },
  {
    name: "Ashley Hinson",
    chamber: "House",
    party: "Republican",
    state: "IA",
    district: "2",
    officialHandle: "RepAshleyHinson",
  },
  { name: "Zach Nunn", chamber: "House", party: "Republican", state: "IA", district: "3", officialHandle: "ZachNunn" },
  {
    name: "Randy Feenstra",
    chamber: "House",
    party: "Republican",
    state: "IA",
    district: "4",
    officialHandle: "RepFeenstra",
  },

  // Idaho
  {
    name: "Russ Fulcher",
    chamber: "House",
    party: "Republican",
    state: "ID",
    district: "1",
    officialHandle: "reprussfulcher",
  },
  {
    name: "Mike Simpson",
    chamber: "House",
    party: "Republican",
    state: "ID",
    district: "2",
    officialHandle: "CongMikeSimpson",
  },

  // Illinois
  {
    name: "Jonathan Jackson",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "1",
    officialHandle: "rep_jackson",
  },
  {
    name: "Robin Kelly",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "2",
    officialHandle: "RepRobinKelly",
  },
  {
    name: "Delia Ramirez",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "3",
    officialHandle: "DeliaRamirezIL",
  },
  {
    name: "Jesús García",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "4",
    officialHandle: "RepChuyGarcia",
  },
  {
    name: "Mike Quigley",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "5",
    officialHandle: "RepMikeQuigley",
  },
  { name: "Sean Casten", chamber: "House", party: "Democrat", state: "IL", district: "6", officialHandle: "RepCasten" },
  {
    name: "Danny Davis",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "7",
    officialHandle: "RepDannyDavis",
  },
  {
    name: "Raja Krishnamoorthi",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "8",
    officialHandle: "congressmanraja",
  },
  {
    name: "Jan Schakowsky",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "9",
    officialHandle: "JanSchakowsky",
  },
  {
    name: "Brad Schneider",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "10",
    officialHandle: "repschneider",
  },
  {
    name: "Bill Foster",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "11",
    officialHandle: "RepBillFoster",
  },
  { name: "Mike Bost", chamber: "House", party: "Republican", state: "IL", district: "12", officialHandle: "RepBost" },
  {
    name: "Nikki Budzinski",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "13",
    officialHandle: "RepNikkiB",
  },
  {
    name: "Lauren Underwood",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "14",
    officialHandle: "RepUnderwood",
  },
  {
    name: "Mary Miller",
    chamber: "House",
    party: "Republican",
    state: "IL",
    district: "15",
    officialHandle: "RepMaryMiller",
  },
  {
    name: "Darin LaHood",
    chamber: "House",
    party: "Republican",
    state: "IL",
    district: "16",
    officialHandle: "RepLaHood",
  },
  {
    name: "Eric Sorensen",
    chamber: "House",
    party: "Democrat",
    state: "IL",
    district: "17",
    officialHandle: "RepEricSorensen",
  },

  // Indiana
  { name: "Frank Mrvan", chamber: "House", party: "Democrat", state: "IN", district: "1", officialHandle: "RepMrvan" },
  {
    name: "Rudy Yakym",
    chamber: "House",
    party: "Republican",
    state: "IN",
    district: "2",
    officialHandle: "RepRudyYakym",
  },
  {
    name: "Marlin Stutzman",
    chamber: "House",
    party: "Republican",
    state: "IN",
    district: "3",
    officialHandle: "RepStutzman",
  },
  {
    name: "Jim Baird",
    chamber: "House",
    party: "Republican",
    state: "IN",
    district: "4",
    officialHandle: "RepJimBaird",
  },
  {
    name: "Victoria Spartz",
    chamber: "House",
    party: "Republican",
    state: "IN",
    district: "5",
    officialHandle: "RepSpartz",
  },
  {
    name: "Jefferson Shreve",
    chamber: "House",
    party: "Republican",
    state: "IN",
    district: "6",
    officialHandle: "RepShreve",
  },
  {
    name: "André Carson",
    chamber: "House",
    party: "Democrat",
    state: "IN",
    district: "7",
    officialHandle: "RepAndreCarson",
  },
  {
    name: "Mark Messmer",
    chamber: "House",
    party: "Republican",
    state: "IN",
    district: "8",
    officialHandle: "RepMessmer",
  },
  {
    name: "Erin Houchin",
    chamber: "House",
    party: "Republican",
    state: "IN",
    district: "9",
    officialHandle: "erin_houchin",
  },

  // Kansas
  { name: "Tracey Mann", chamber: "House", party: "Republican", state: "KS", district: "1", officialHandle: "RepMann" },
  {
    name: "Derek Schmidt",
    chamber: "House",
    party: "Republican",
    state: "KS",
    district: "2",
    officialHandle: "RepDerekSchmidt",
  },
  {
    name: "Sharice Davids",
    chamber: "House",
    party: "Democrat",
    state: "KS",
    district: "3",
    officialHandle: "RepDavids",
  },
  {
    name: "Ron Estes",
    chamber: "House",
    party: "Republican",
    state: "KS",
    district: "4",
    officialHandle: "RepRonEstes",
  },

  // Kentucky
  {
    name: "James Comer",
    chamber: "House",
    party: "Republican",
    state: "KY",
    district: "1",
    officialHandle: "RepJamesComer",
  },
  {
    name: "Brett Guthrie",
    chamber: "House",
    party: "Republican",
    state: "KY",
    district: "2",
    officialHandle: "RepGuthrie",
  },
  {
    name: "Morgan McGarvey",
    chamber: "House",
    party: "Democrat",
    state: "KY",
    district: "3",
    officialHandle: "RepMcGarvey",
  },
  {
    name: "Thomas Massie",
    chamber: "House",
    party: "Republican",
    state: "KY",
    district: "4",
    officialHandle: "RepThomasMassie",
  },
  {
    name: "Hal Rogers",
    chamber: "House",
    party: "Republican",
    state: "KY",
    district: "5",
    officialHandle: "RepHalRogers",
  },
  {
    name: "Andy Barr",
    chamber: "House",
    party: "Republican",
    state: "KY",
    district: "6",
    officialHandle: "RepAndyBarr",
  },

  // Louisiana
  {
    name: "Steve Scalise",
    chamber: "House",
    party: "Republican",
    state: "LA",
    district: "1",
    officialHandle: "SteveScalise",
  },
  {
    name: "Troy Carter",
    chamber: "House",
    party: "Democrat",
    state: "LA",
    district: "2",
    officialHandle: "RepTroyCarter",
  },
  {
    name: "Clay Higgins",
    chamber: "House",
    party: "Republican",
    state: "LA",
    district: "3",
    officialHandle: "RepClayHiggins",
  },
  {
    name: "Mike Johnson",
    chamber: "House",
    party: "Republican",
    state: "LA",
    district: "4",
    officialHandle: "RepMikeJohnson",
  },
  {
    name: "Julia Letlow",
    chamber: "House",
    party: "Republican",
    state: "LA",
    district: "5",
    officialHandle: "repjulialetlow",
  },
  {
    name: "Cleo Fields",
    chamber: "House",
    party: "Democrat",
    state: "LA",
    district: "6",
    officialHandle: "realCleoFields",
  },

  // Massachusetts
  {
    name: "Richard Neal",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "1",
    officialHandle: "RepRichardNeal",
  },
  {
    name: "Jim McGovern",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "2",
    officialHandle: "RepMcGovern",
  },
  {
    name: "Lori Trahan",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "3",
    officialHandle: "RepLoriTrahan",
  },
  {
    name: "Jake Auchincloss",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "4",
    officialHandle: "RepAuchincloss",
  },
  {
    name: "Katherine Clark",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "5",
    officialHandle: "RepKClark",
  },
  {
    name: "Seth Moulton",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "6",
    officialHandle: "teammoulton",
  },
  {
    name: "Ayanna Pressley",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "7",
    officialHandle: "RepPressley",
  },
  {
    name: "Stephen Lynch",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "8",
    officialHandle: "RepStephenLynch",
  },
  {
    name: "Bill Keating",
    chamber: "House",
    party: "Democrat",
    state: "MA",
    district: "9",
    officialHandle: "USRepKeating",
  },

  // Maryland
  {
    name: "Andy Harris",
    chamber: "House",
    party: "Republican",
    state: "MD",
    district: "1",
    officialHandle: "RepAndyHarrisMD",
  },
  {
    name: "Johnny Olszewski",
    chamber: "House",
    party: "Democrat",
    state: "MD",
    district: "2",
    officialHandle: "RepJohnnyO",
  },
  {
    name: "Sarah Elfreth",
    chamber: "House",
    party: "Democrat",
    state: "MD",
    district: "3",
    officialHandle: "RepSarahElfreth",
  },
  {
    name: "Glenn Ivey",
    chamber: "House",
    party: "Democrat",
    state: "MD",
    district: "4",
    officialHandle: "glenniveymd",
  },
  { name: "Steny Hoyer", chamber: "House", party: "Democrat", state: "MD", district: "5", officialHandle: "WhipHoyer" },
  {
    name: "April McClain-Delaney",
    chamber: "House",
    party: "Democrat",
    state: "MD",
    district: "6",
    officialHandle: "RepAprilDelaney",
  },
  {
    name: "Kweisi Mfume",
    chamber: "House",
    party: "Democrat",
    state: "MD",
    district: "7",
    officialHandle: "repkweisimfume",
  },
  {
    name: "Jamie Raskin",
    chamber: "House",
    party: "Democrat",
    state: "MD",
    district: "8",
    officialHandle: "repraskin",
  },

  // Maine
  {
    name: "Chellie Pingree",
    chamber: "House",
    party: "Democrat",
    state: "ME",
    district: "1",
    officialHandle: "ChelliePingree",
  },
  {
    name: "Jared Golden",
    chamber: "House",
    party: "Democrat",
    state: "ME",
    district: "2",
    officialHandle: "RepGolden",
  },

  // Michigan
  {
    name: "Jack Bergman",
    chamber: "House",
    party: "Republican",
    state: "MI",
    district: "1",
    officialHandle: "RepJackBergman",
  },
  {
    name: "John Moolenaar",
    chamber: "House",
    party: "Republican",
    state: "MI",
    district: "2",
    officialHandle: "RepMoolenaar",
  },
  {
    name: "Hillary Scholten",
    chamber: "House",
    party: "Democrat",
    state: "MI",
    district: "3",
    officialHandle: "RepScholten",
  },
  {
    name: "Bill Huizenga",
    chamber: "House",
    party: "Republican",
    state: "MI",
    district: "4",
    officialHandle: "RepHuizenga",
  },
  {
    name: "Tim Walberg",
    chamber: "House",
    party: "Republican",
    state: "MI",
    district: "5",
    officialHandle: "RepWalberg",
  },
  {
    name: "Debbie Dingell",
    chamber: "House",
    party: "Democrat",
    state: "MI",
    district: "6",
    officialHandle: "RepDebDingell",
  },
  {
    name: "Tom Barrett",
    chamber: "House",
    party: "Republican",
    state: "MI",
    district: "7",
    officialHandle: "RepTomBarrett",
  },
  {
    name: "Kristen McDonald Rivet",
    chamber: "House",
    party: "Democrat",
    state: "MI",
    district: "8",
    officialHandle: "repkmr",
  },
  {
    name: "Lisa McClain",
    chamber: "House",
    party: "Republican",
    state: "MI",
    district: "9",
    officialHandle: "RepLisaMcClain",
  },
  {
    name: "John James",
    chamber: "House",
    party: "Republican",
    state: "MI",
    district: "10",
    officialHandle: "JohnJamesMI",
  },
  {
    name: "Haley Stevens",
    chamber: "House",
    party: "Democrat",
    state: "MI",
    district: "11",
    officialHandle: "RepHaleyStevens",
  },
  {
    name: "Rashida Tlaib",
    chamber: "House",
    party: "Democrat",
    state: "MI",
    district: "12",
    officialHandle: "RepRashida",
  },
  {
    name: "Shri Thanedar",
    chamber: "House",
    party: "Democrat",
    state: "MI",
    district: "13",
    officialHandle: "RepShriThanedar",
  },

  // Minnesota
  {
    name: "Brad Finstad",
    chamber: "House",
    party: "Republican",
    state: "MN",
    district: "1",
    officialHandle: "RepFinstad",
  },
  {
    name: "Angie Craig",
    chamber: "House",
    party: "Democrat",
    state: "MN",
    district: "2",
    officialHandle: "RepAngieCraig",
  },
  {
    name: "Kelly Morrison",
    chamber: "House",
    party: "Democrat",
    state: "MN",
    district: "3",
    officialHandle: "Morrison4MN",
  },
  {
    name: "Betty McCollum",
    chamber: "House",
    party: "Democrat",
    state: "MN",
    district: "4",
    officialHandle: "BettyMcCollum04",
  },
  { name: "Ilhan Omar", chamber: "House", party: "Democrat", state: "MN", district: "5", officialHandle: "Ilhan" },
  {
    name: "Tom Emmer",
    chamber: "House",
    party: "Republican",
    state: "MN",
    district: "6",
    officialHandle: "RepTomEmmer",
  },
  {
    name: "Michelle Fischbach",
    chamber: "House",
    party: "Republican",
    state: "MN",
    district: "7",
    officialHandle: "RepFischbach",
  },
  {
    name: "Pete Stauber",
    chamber: "House",
    party: "Republican",
    state: "MN",
    district: "8",
    officialHandle: "RepPeteStauber",
  },

  // Missouri
  {
    name: "Wesley Bell",
    chamber: "House",
    party: "Democrat",
    state: "MO",
    district: "1",
    officialHandle: "RepWesleyBellMO",
  },
  {
    name: "Ann Wagner",
    chamber: "House",
    party: "Republican",
    state: "MO",
    district: "2",
    officialHandle: "RepAnnWagner",
  },
  {
    name: "Bob Onder",
    chamber: "House",
    party: "Republican",
    state: "MO",
    district: "3",
    officialHandle: "RepBobOnder",
  },
  {
    name: "Mark Alford",
    chamber: "House",
    party: "Republican",
    state: "MO",
    district: "4",
    officialHandle: "RepMarkAlford",
  },
  {
    name: "Emanuel Cleaver",
    chamber: "House",
    party: "Democrat",
    state: "MO",
    district: "5",
    officialHandle: "RepCleaver",
  },
  {
    name: "Sam Graves",
    chamber: "House",
    party: "Republican",
    state: "MO",
    district: "6",
    officialHandle: "RepSamGraves",
  },
  {
    name: "Eric Burlison",
    chamber: "House",
    party: "Republican",
    state: "MO",
    district: "7",
    officialHandle: "RepEricBurlison",
  },
  {
    name: "Jason Smith",
    chamber: "House",
    party: "Republican",
    state: "MO",
    district: "8",
    officialHandle: "RepJasonSmith",
  },

  // Mississippi
  {
    name: "Trent Kelly",
    chamber: "House",
    party: "Republican",
    state: "MS",
    district: "1",
    officialHandle: "reptrentkelly",
  },
  {
    name: "Bennie Thompson",
    chamber: "House",
    party: "Democrat",
    state: "MS",
    district: "2",
    officialHandle: "BennieGThompson",
  },
  {
    name: "Michael Guest",
    chamber: "House",
    party: "Republican",
    state: "MS",
    district: "3",
    officialHandle: "RepMichaelGuest",
  },
  { name: "Mike Ezell", chamber: "House", party: "Republican", state: "MS", district: "4", officialHandle: "repezell" },

  // Montana
  {
    name: "Ryan Zinke",
    chamber: "House",
    party: "Republican",
    state: "MT",
    district: "1",
    officialHandle: "RepRyanZinke",
  },
  {
    name: "Troy Downing",
    chamber: "House",
    party: "Republican",
    state: "MT",
    district: "2",
    officialHandle: "RepTroyDowning",
  },

  // North Carolina
  { name: "Don Davis", chamber: "House", party: "Democrat", state: "NC", district: "1", officialHandle: "DonDavisNC" },
  {
    name: "Deborah Ross",
    chamber: "House",
    party: "Democrat",
    state: "NC",
    district: "2",
    officialHandle: "RepDeborahRoss",
  },
  {
    name: "Greg Murphy",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "3",
    officialHandle: "RepGregMurphy",
  },
  {
    name: "Valerie Foushee",
    chamber: "House",
    party: "Democrat",
    state: "NC",
    district: "4",
    officialHandle: "ValerieFoushee",
  },
  {
    name: "Virginia Foxx",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "5",
    officialHandle: "VirginiaFoxx",
  },
  {
    name: "Addison McDowell",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "6",
    officialHandle: "RepMcDowell",
  },
  {
    name: "David Rouzer",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "7",
    officialHandle: "RepDavidRouzer",
  },
  {
    name: "Mark Harris",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "8",
    officialHandle: "RepMarkHarrisNC",
  },
  {
    name: "Richard Hudson",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "9",
    officialHandle: "RepRichHudson",
  },
  {
    name: "Pat Harrigan",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "10",
    officialHandle: "RepPatHarrigan",
  },
  {
    name: "Chuck Edwards",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "11",
    officialHandle: "RepEdwards",
  },
  { name: "Alma Adams", chamber: "House", party: "Democrat", state: "NC", district: "12", officialHandle: "RepAdams" },
  {
    name: "Brad Knott",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "13",
    officialHandle: "RepKnott",
  },
  {
    name: "Tim Moore",
    chamber: "House",
    party: "Republican",
    state: "NC",
    district: "14",
    officialHandle: "RepTimMooreNC",
  },

  // North Dakota
  {
    name: "Julie Fedorchak",
    chamber: "House",
    party: "Republican",
    state: "ND",
    district: "At-Large",
    officialHandle: "RepFedorchak",
  },

  // Nebraska
  {
    name: "Mike Flood",
    chamber: "House",
    party: "Republican",
    state: "NE",
    district: "1",
    officialHandle: "RepMikeFlood",
  },
  {
    name: "Don Bacon",
    chamber: "House",
    party: "Republican",
    state: "NE",
    district: "2",
    officialHandle: "RepDonBacon",
  },
  {
    name: "Adrian Smith",
    chamber: "House",
    party: "Republican",
    state: "NE",
    district: "3",
    officialHandle: "RepAdrianSmith",
  },

  // New Hampshire
  {
    name: "Chris Pappas",
    chamber: "House",
    party: "Democrat",
    state: "NH",
    district: "1",
    officialHandle: "RepChrisPappas",
  },
  {
    name: "Maggie Goodlander",
    chamber: "House",
    party: "Democrat",
    state: "NH",
    district: "2",
    officialHandle: "RepGoodlander",
  },

  // New Jersey
  {
    name: "Donald Norcross",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "1",
    officialHandle: "DonaldNorcross",
  },
  {
    name: "Jeff Van Drew",
    chamber: "House",
    party: "Republican",
    state: "NJ",
    district: "2",
    officialHandle: "CongressmanJVD",
  },
  {
    name: "Herb Conaway",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "3",
    officialHandle: "RepHerbConaway",
  },
  {
    name: "Chris Smith",
    chamber: "House",
    party: "Republican",
    state: "NJ",
    district: "4",
    officialHandle: "RepChrisSmith",
  },
  {
    name: "Josh Gottheimer",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "5",
    officialHandle: "RepJoshG",
  },
  {
    name: "Frank Pallone",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "6",
    officialHandle: "FrankPallone",
  },
  {
    name: "Tom Kean Jr.",
    chamber: "House",
    party: "Republican",
    state: "NJ",
    district: "7",
    officialHandle: "CongressmanKean",
  },
  {
    name: "Rob Menendez",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "8",
    officialHandle: "RepMenendez",
  },
  { name: "Nellie Pou", chamber: "House", party: "Democrat", state: "NJ", district: "9", officialHandle: "NelliePou" },
  {
    name: "LaMonica McIver",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "10",
    officialHandle: "RepMcIver",
  },
  {
    name: "Mikie Sherrill",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "11",
    officialHandle: "RepSherrill",
  },
  {
    name: "Bonnie Watson Coleman",
    chamber: "House",
    party: "Democrat",
    state: "NJ",
    district: "12",
    officialHandle: "RepBonnie",
  },

  // New Mexico
  {
    name: "Melanie Stansbury",
    chamber: "House",
    party: "Democrat",
    state: "NM",
    district: "1",
    officialHandle: "RepStansbury",
  },
  {
    name: "Gabe Vasquez",
    chamber: "House",
    party: "Democrat",
    state: "NM",
    district: "2",
    officialHandle: "RepGabeVasquez",
  },
  {
    name: "Teresa Leger Fernández",
    chamber: "House",
    party: "Democrat",
    state: "NM",
    district: "3",
    officialHandle: "RepTeresaLF",
  },

  // Nevada
  {
    name: "Dina Titus",
    chamber: "House",
    party: "Democrat",
    state: "NV",
    district: "1",
    officialHandle: "repdinatitus",
  },
  {
    name: "Mark Amodei",
    chamber: "House",
    party: "Republican",
    state: "NV",
    district: "2",
    officialHandle: "MarkAmodeiNV2",
  },
  { name: "Susie Lee", chamber: "House", party: "Democrat", state: "NV", district: "3", officialHandle: "RepSusieLee" },
  {
    name: "Steven Horsford",
    chamber: "House",
    party: "Democrat",
    state: "NV",
    district: "4",
    officialHandle: "RepHorsford",
  },

  // New York
  {
    name: "Nick LaLota",
    chamber: "House",
    party: "Republican",
    state: "NY",
    district: "1",
    officialHandle: "RepLaLota",
  },
  {
    name: "Andrew Garbarino",
    chamber: "House",
    party: "Republican",
    state: "NY",
    district: "2",
    officialHandle: "RepGarbarino",
  },
  {
    name: "Tom Suozzi",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "3",
    officialHandle: "RepTomSuozzi",
  },
  {
    name: "Laura Gillen",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "4",
    officialHandle: "RepLauraGillen",
  },
  {
    name: "Gregory Meeks",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "5",
    officialHandle: "RepGregoryMeeks",
  },
  {
    name: "Grace Meng",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "6",
    officialHandle: "RepGraceMeng",
  },
  {
    name: "Nydia Velázquez",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "7",
    officialHandle: "NydiaVelazquez",
  },
  {
    name: "Hakeem Jeffries",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "8",
    officialHandle: "RepJeffries",
  },
  {
    name: "Yvette Clarke",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "9",
    officialHandle: "RepYvetteClarke",
  },
  {
    name: "Dan Goldman",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "10",
    officialHandle: "RepDanGoldman",
  },
  {
    name: "Nicole Malliotakis",
    chamber: "House",
    party: "Republican",
    state: "NY",
    district: "11",
    officialHandle: "RepMalliotakis",
  },
  {
    name: "Jerrold Nadler",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "12",
    officialHandle: "RepJerryNadler",
  },
  {
    name: "Adriano Espaillat",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "13",
    officialHandle: "RepEspaillat",
  },
  {
    name: "Alexandria Ocasio-Cortez",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "14",
    officialHandle: "RepAOC",
  },
  {
    name: "Ritchie Torres",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "15",
    officialHandle: "RepRitchie",
  },
  {
    name: "George Latimer",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "16",
    officialHandle: "RepGLatimer",
  },
  {
    name: "Mike Lawler",
    chamber: "House",
    party: "Republican",
    state: "NY",
    district: "17",
    officialHandle: "RepMikeLawler",
  },
  {
    name: "Pat Ryan",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "18",
    officialHandle: "RepPatRyanNY",
  },
  {
    name: "Josh Riley",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "19",
    officialHandle: "RepRileyNY",
  },
  {
    name: "Paul Tonko",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "20",
    officialHandle: "RepPaulTonko",
  },
  {
    name: "Elise Stefanik",
    chamber: "House",
    party: "Republican",
    state: "NY",
    district: "21",
    officialHandle: "RepStefanik",
  },
  {
    name: "John Mannion",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "22",
    officialHandle: "JohnMannionNY22",
  },
  {
    name: "Nick Langworthy",
    chamber: "House",
    party: "Republican",
    state: "NY",
    district: "23",
    officialHandle: "RepLangworthy",
  },
  {
    name: "Claudia Tenney",
    chamber: "House",
    party: "Republican",
    state: "NY",
    district: "24",
    officialHandle: "RepTenney",
  },
  {
    name: "Joe Morelle",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "25",
    officialHandle: "RepJoeMorelle",
  },
  {
    name: "Tim Kennedy",
    chamber: "House",
    party: "Democrat",
    state: "NY",
    district: "26",
    officialHandle: "RepTimKennedy",
  },

  // Ohio
  {
    name: "Greg Landsman",
    chamber: "House",
    party: "Democrat",
    state: "OH",
    district: "1",
    officialHandle: "RepGregLandsman",
  },
  {
    name: "Brad Wenstrup",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "2",
    officialHandle: "RepBradWenstrup",
  },
  {
    name: "Joyce Beatty",
    chamber: "House",
    party: "Democrat",
    state: "OH",
    district: "3",
    officialHandle: "RepBeatty",
  },
  {
    name: "Jim Jordan",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "4",
    officialHandle: "Jim_Jordan",
  },
  { name: "Bob Latta", chamber: "House", party: "Republican", state: "OH", district: "5", officialHandle: "BobLatta" },
  {
    name: "Michael Rulli",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "6",
    officialHandle: "RepRulli",
  },
  {
    name: "Max Miller",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "7",
    officialHandle: "RepMaxMiller",
  },
  {
    name: "Warren Davidson",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "8",
    officialHandle: "WarrenDavidson",
  },
  {
    name: "Marcy Kaptur",
    chamber: "House",
    party: "Democrat",
    state: "OH",
    district: "9",
    officialHandle: "RepMarcyKaptur",
  },
  {
    name: "Mike Turner",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "10",
    officialHandle: "RepMikeTurner",
  },
  {
    name: "Shontel Brown",
    chamber: "House",
    party: "Democrat",
    state: "OH",
    district: "11",
    officialHandle: "RepShontelBrown",
  },
  {
    name: "Troy Balderson",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "12",
    officialHandle: "RepBalderson",
  },
  {
    name: "Emilia Sykes",
    chamber: "House",
    party: "Democrat",
    state: "OH",
    district: "13",
    officialHandle: "RepEmiliaSykes",
  },
  {
    name: "David Joyce",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "14",
    officialHandle: "RepDaveJoyce",
  },
  {
    name: "Mike Carey",
    chamber: "House",
    party: "Republican",
    state: "OH",
    district: "15",
    officialHandle: "RepMikeCarey",
  },

  // Oklahoma
  {
    name: "Kevin Hern",
    chamber: "House",
    party: "Republican",
    state: "OK",
    district: "1",
    officialHandle: "repkevinhern",
  },
  {
    name: "Josh Brecheen",
    chamber: "House",
    party: "Republican",
    state: "OK",
    district: "2",
    officialHandle: "RepBrecheen",
  },
  {
    name: "Frank Lucas",
    chamber: "House",
    party: "Republican",
    state: "OK",
    district: "3",
    officialHandle: "RepFrankLucas",
  },
  {
    name: "Tom Cole",
    chamber: "House",
    party: "Republican",
    state: "OK",
    district: "4",
    officialHandle: "TomColeOK04",
  },
  {
    name: "Stephanie Bice",
    chamber: "House",
    party: "Republican",
    state: "OK",
    district: "5",
    officialHandle: "RepBice",
  },

  // Oregon
  {
    name: "Suzanne Bonamici",
    chamber: "House",
    party: "Democrat",
    state: "OR",
    district: "1",
    officialHandle: "RepBonamici",
  },
  {
    name: "Cliff Bentz",
    chamber: "House",
    party: "Republican",
    state: "OR",
    district: "2",
    officialHandle: "RepBentz",
  },
  {
    name: "Maxine Dexter",
    chamber: "House",
    party: "Democrat",
    state: "OR",
    district: "3",
    officialHandle: "RepDexterOR",
  },
  { name: "Val Hoyle", chamber: "House", party: "Democrat", state: "OR", district: "4", officialHandle: "RepValHoyle" },
  {
    name: "Janelle Bynum",
    chamber: "House",
    party: "Democrat",
    state: "OR",
    district: "5",
    officialHandle: "RepBynum",
  },
  {
    name: "Andrea Salinas",
    chamber: "House",
    party: "Democrat",
    state: "OR",
    district: "6",
    officialHandle: "RepSalinas",
  },

  // Pennsylvania
  {
    name: "Brian Fitzpatrick",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "1",
    officialHandle: "RepBrianFitz",
  },
  {
    name: "Brendan Boyle",
    chamber: "House",
    party: "Democrat",
    state: "PA",
    district: "2",
    officialHandle: "CongBoyle",
  },
  {
    name: "Dwight Evans",
    chamber: "House",
    party: "Democrat",
    state: "PA",
    district: "3",
    officialHandle: "RepDwightEvans",
  },
  {
    name: "Madeleine Dean",
    chamber: "House",
    party: "Democrat",
    state: "PA",
    district: "4",
    officialHandle: "RepDean",
  },
  {
    name: "Mary Gay Scanlon",
    chamber: "House",
    party: "Democrat",
    state: "PA",
    district: "5",
    officialHandle: "RepScanlon",
  },
  {
    name: "Chrissy Houlahan",
    chamber: "House",
    party: "Democrat",
    state: "PA",
    district: "6",
    officialHandle: "RepHoulahan",
  },
  {
    name: "Ryan Mackenzie",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "7",
    officialHandle: "RepMackenzie",
  },
  {
    name: "Rob Bresnahan",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "8",
    officialHandle: "RepBresnahan",
  },
  {
    name: "Dan Meuser",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "9",
    officialHandle: "RepMeuser",
  },
  {
    name: "Scott Perry",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "10",
    officialHandle: "RepScottPerry",
  },
  {
    name: "Lloyd Smucker",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "11",
    officialHandle: "RepSmucker",
  },
  {
    name: "Summer Lee",
    chamber: "House",
    party: "Democrat",
    state: "PA",
    district: "12",
    officialHandle: "RepSummerLee",
  },
  {
    name: "John Joyce",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "13",
    officialHandle: "RepJohnJoyce",
  },
  {
    name: "Guy Reschenthaler",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "14",
    officialHandle: "GReschenthaler",
  },
  {
    name: "Glenn Thompson",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "15",
    officialHandle: "CongressmanGT",
  },
  {
    name: "Mike Kelly",
    chamber: "House",
    party: "Republican",
    state: "PA",
    district: "16",
    officialHandle: "MikeKellyPA",
  },
  {
    name: "Chris Deluzio",
    chamber: "House",
    party: "Democrat",
    state: "PA",
    district: "17",
    officialHandle: "RepDeluzio",
  },

  // Rhode Island
  { name: "Gabe Amo", chamber: "House", party: "Democrat", state: "RI", district: "1", officialHandle: "RepGabeAmo" },
  {
    name: "Seth Magaziner",
    chamber: "House",
    party: "Democrat",
    state: "RI",
    district: "2",
    officialHandle: "Rep_Magaziner",
  },

  // South Carolina
  {
    name: "Nancy Mace",
    chamber: "House",
    party: "Republican",
    state: "SC",
    district: "1",
    officialHandle: "RepNancyMace",
  },
  {
    name: "Joe Wilson",
    chamber: "House",
    party: "Republican",
    state: "SC",
    district: "2",
    officialHandle: "RepJoeWilson",
  },
  {
    name: "Sheri Biggs",
    chamber: "House",
    party: "Republican",
    state: "SC",
    district: "3",
    officialHandle: "RepSheriBiggs",
  },
  {
    name: "William Timmons",
    chamber: "House",
    party: "Republican",
    state: "SC",
    district: "4",
    officialHandle: "RepTimmons",
  },
  {
    name: "Ralph Norman",
    chamber: "House",
    party: "Republican",
    state: "SC",
    district: "5",
    officialHandle: "RepRalphNorman",
  },
  {
    name: "James Clyburn",
    chamber: "House",
    party: "Democrat",
    state: "SC",
    district: "6",
    officialHandle: "RepJamesClyburn",
  },
  {
    name: "Russell Fry",
    chamber: "House",
    party: "Republican",
    state: "SC",
    district: "7",
    officialHandle: "RepRussellFry",
  },

  // Tennessee
  {
    name: "Diana Harshbarger",
    chamber: "House",
    party: "Republican",
    state: "TN",
    district: "1",
    officialHandle: "RepHarshbarger",
  },
  {
    name: "Tim Burchett",
    chamber: "House",
    party: "Republican",
    state: "TN",
    district: "2",
    officialHandle: "RepTimBurchett",
  },
  {
    name: "Chuck Fleischmann",
    chamber: "House",
    party: "Republican",
    state: "TN",
    district: "3",
    officialHandle: "RepChuck",
  },
  {
    name: "Scott DesJarlais",
    chamber: "House",
    party: "Republican",
    state: "TN",
    district: "4",
    officialHandle: "DesJarlaisTN04",
  },
  { name: "Andy Ogles", chamber: "House", party: "Republican", state: "TN", district: "5", officialHandle: "RepOgles" },
  {
    name: "John Rose",
    chamber: "House",
    party: "Republican",
    state: "TN",
    district: "6",
    officialHandle: "RepJohnRose",
  },
  {
    name: "Mark Green",
    chamber: "House",
    party: "Republican",
    state: "TN",
    district: "7",
    officialHandle: "RepMarkGreenTN",
  },
  {
    name: "David Kustoff",
    chamber: "House",
    party: "Republican",
    state: "TN",
    district: "8",
    officialHandle: "RepDavidKustoff",
  },
  { name: "Steve Cohen", chamber: "House", party: "Democrat", state: "TN", district: "9", officialHandle: "RepCohen" },

  // Texas
  {
    name: "Nathaniel Moran",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "1",
    officialHandle: "RepNMoran",
  },
  {
    name: "Dan Crenshaw",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "2",
    officialHandle: "RepDanCrenshaw",
  },
  {
    name: "Keith Self",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "3",
    officialHandle: "RepKeithSelf",
  },
  {
    name: "Pat Fallon",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "4",
    officialHandle: "RepPatFallon",
  },
  {
    name: "Lance Gooden",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "5",
    officialHandle: "RepLanceGooden",
  },
  {
    name: "Jake Ellzey",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "6",
    officialHandle: "RepEllzey",
  },
  {
    name: "Lizzie Fletcher",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "7",
    officialHandle: "RepFletcher",
  },
  {
    name: "Morgan Luttrell",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "8",
    officialHandle: "RepLuttrell",
  },
  { name: "Al Green", chamber: "House", party: "Democrat", state: "TX", district: "9", officialHandle: "RepAlGreen" },
  {
    name: "Michael McCaul",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "10",
    officialHandle: "RepMcCaul",
  },
  {
    name: "August Pfluger",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "11",
    officialHandle: "RepPfluger",
  },
  {
    name: "Craig Goldman",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "12",
    officialHandle: "RepCraigGoldman",
  },
  {
    name: "Ronny Jackson",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "13",
    officialHandle: "RepRonnyJackson",
  },
  {
    name: "Randy Weber",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "14",
    officialHandle: "TXRandy14",
  },
  {
    name: "Monica De La Cruz",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "15",
    officialHandle: "RepMonicaDLC",
  },
  {
    name: "Veronica Escobar",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "16",
    officialHandle: "RepEscobar",
  },
  {
    name: "Pete Sessions",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "17",
    officialHandle: "PeteSessions",
  },
  {
    name: "Jodey Arrington",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "19",
    officialHandle: "RepArrington",
  },
  {
    name: "Joaquin Castro",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "20",
    officialHandle: "JoaquinCastrotx",
  },
  {
    name: "Chip Roy",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "21",
    officialHandle: "RepChipRoy",
  },
  {
    name: "Troy Nehls",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "22",
    officialHandle: "RepTroyNehls",
  },
  {
    name: "Tony Gonzales",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "23",
    officialHandle: "RepTonyGonzales",
  },
  {
    name: "Beth Van Duyne",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "24",
    officialHandle: "RepBethVanDuyne",
  },
  {
    name: "Roger Williams",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "25",
    officialHandle: "RepRWilliams",
  },
  {
    name: "Brandon Gill",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "26",
    officialHandle: "RepBrandonGill",
  },
  {
    name: "Michael Cloud",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "27",
    officialHandle: "RepCloudTX",
  },
  {
    name: "Henry Cuellar",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "28",
    officialHandle: "RepCuellar",
  },
  {
    name: "Sylvia Garcia",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "29",
    officialHandle: "RepSylviaGarcia",
  },
  {
    name: "Jasmine Crockett",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "30",
    officialHandle: "RepJasmine",
  },
  {
    name: "John Carter",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "31",
    officialHandle: "RepJohnCarter",
  },
  {
    name: "Colin Allred",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "32",
    officialHandle: "RepColinAllred",
  },
  {
    name: "Marc Veasey",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "33",
    officialHandle: "RepVeasey",
  },
  {
    name: "Vicente Gonzalez",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "34",
    officialHandle: "RepGonzalez",
  },
  { name: "Greg Casar", chamber: "House", party: "Democrat", state: "TX", district: "35", officialHandle: "RepCasar" },
  {
    name: "Brian Babin",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "36",
    officialHandle: "RepBrianBabin",
  },
  {
    name: "Lloyd Doggett",
    chamber: "House",
    party: "Democrat",
    state: "TX",
    district: "37",
    officialHandle: "RepLloydDoggett",
  },
  {
    name: "Wesley Hunt",
    chamber: "House",
    party: "Republican",
    state: "TX",
    district: "38",
    officialHandle: "RepWesleyHunt",
  },

  // Utah
  {
    name: "Blake Moore",
    chamber: "House",
    party: "Republican",
    state: "UT",
    district: "1",
    officialHandle: "RepBlakeMoore",
  },
  {
    name: "Celeste Maloy",
    chamber: "House",
    party: "Republican",
    state: "UT",
    district: "2",
    officialHandle: "RepMaloy",
  },
  {
    name: "Mike Kennedy",
    chamber: "House",
    party: "Republican",
    state: "UT",
    district: "3",
    officialHandle: "RepMikeKennedy",
  },
  {
    name: "Burgess Owens",
    chamber: "House",
    party: "Republican",
    state: "UT",
    district: "4",
    officialHandle: "RepBurgessOwens",
  },

  // Virginia
  {
    name: "Rob Wittman",
    chamber: "House",
    party: "Republican",
    state: "VA",
    district: "1",
    officialHandle: "RobWittman",
  },
  {
    name: "Jen Kiggans",
    chamber: "House",
    party: "Republican",
    state: "VA",
    district: "2",
    officialHandle: "RepJenKiggans",
  },
  {
    name: "Bobby Scott",
    chamber: "House",
    party: "Democrat",
    state: "VA",
    district: "3",
    officialHandle: "BobbyScott",
  },
  {
    name: "Jennifer McClellan",
    chamber: "House",
    party: "Democrat",
    state: "VA",
    district: "4",
    officialHandle: "RepMcClellan",
  },
  {
    name: "John McGuire",
    chamber: "House",
    party: "Republican",
    state: "VA",
    district: "5",
    officialHandle: "RepJohnMcGuire",
  },
  {
    name: "Ben Cline",
    chamber: "House",
    party: "Republican",
    state: "VA",
    district: "6",
    officialHandle: "RepBenCline",
  },
  {
    name: "Eugene Vindman",
    chamber: "House",
    party: "Democrat",
    state: "VA",
    district: "7",
    officialHandle: "RepVindman",
  },
  { name: "Don Beyer", chamber: "House", party: "Democrat", state: "VA", district: "8", officialHandle: "RepDonBeyer" },
  {
    name: "Morgan Griffith",
    chamber: "House",
    party: "Republican",
    state: "VA",
    district: "9",
    officialHandle: "RepMGriffith",
  },
  {
    name: "Suhas Subramanyam",
    chamber: "House",
    party: "Democrat",
    state: "VA",
    district: "10",
    officialHandle: "RepSuhas",
  },
  {
    name: "Gerry Connolly",
    chamber: "House",
    party: "Democrat",
    state: "VA",
    district: "11",
    officialHandle: "GerryConnolly",
  },

  // Vermont
  {
    name: "Becca Balint",
    chamber: "House",
    party: "Democrat",
    state: "VT",
    district: "At-Large",
    officialHandle: "RepBeccaBalint",
  },

  // Washington
  {
    name: "Suzan DelBene",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "1",
    officialHandle: "RepDelBene",
  },
  {
    name: "Rick Larsen",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "2",
    officialHandle: "RepRickLarsen",
  },
  {
    name: "Marie Gluesenkamp Perez",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "3",
    officialHandle: "RepMGP",
  },
  {
    name: "Dan Newhouse",
    chamber: "House",
    party: "Republican",
    state: "WA",
    district: "4",
    officialHandle: "RepNewhouse",
  },
  {
    name: "Michael Baumgartner",
    chamber: "House",
    party: "Republican",
    state: "WA",
    district: "5",
    officialHandle: "RepBaumgartner",
  },
  {
    name: "Emily Randall",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "6",
    officialHandle: "RepEmilyRandall",
  },
  {
    name: "Pramila Jayapal",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "7",
    officialHandle: "RepJayapal",
  },
  {
    name: "Kim Schrier",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "8",
    officialHandle: "RepKimSchrier",
  },
  {
    name: "Adam Smith",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "9",
    officialHandle: "RepAdamSmith",
  },
  {
    name: "Marilyn Strickland",
    chamber: "House",
    party: "Democrat",
    state: "WA",
    district: "10",
    officialHandle: "RepStricklandWA",
  },

  // Wisconsin
  {
    name: "Bryan Steil",
    chamber: "House",
    party: "Republican",
    state: "WI",
    district: "1",
    officialHandle: "RepBryanSteil",
  },
  {
    name: "Mark Pocan",
    chamber: "House",
    party: "Democrat",
    state: "WI",
    district: "2",
    officialHandle: "RepMarkPocan",
  },
  {
    name: "Derrick Van Orden",
    chamber: "House",
    party: "Republican",
    state: "WI",
    district: "3",
    officialHandle: "RepVanOrden",
  },
  {
    name: "Gwen Moore",
    chamber: "House",
    party: "Democrat",
    state: "WI",
    district: "4",
    officialHandle: "RepGwenMoore",
  },
  {
    name: "Scott Fitzgerald",
    chamber: "House",
    party: "Republican",
    state: "WI",
    district: "5",
    officialHandle: "RepFitzgerald",
  },
  {
    name: "Glenn Grothman",
    chamber: "House",
    party: "Republican",
    state: "WI",
    district: "6",
    officialHandle: "RepGrothman",
  },
  {
    name: "Tom Tiffany",
    chamber: "House",
    party: "Republican",
    state: "WI",
    district: "7",
    officialHandle: "RepTiffany",
  },
  {
    name: "Tony Wied",
    chamber: "House",
    party: "Republican",
    state: "WI",
    district: "8",
    officialHandle: "RepTonyWied",
  },

  // West Virginia
  {
    name: "Carol Miller",
    chamber: "House",
    party: "Republican",
    state: "WV",
    district: "1",
    officialHandle: "RepCarolMiller",
  },
  {
    name: "Alex Mooney",
    chamber: "House",
    party: "Republican",
    state: "WV",
    district: "2",
    officialHandle: "RepMooney",
  },

  // Wyoming
  {
    name: "Harriet Hageman",
    chamber: "House",
    party: "Republican",
    state: "WY",
    district: "At-Large",
    officialHandle: "RepHageman",
  },

  // American Samoa
  {
    name: "Aumua Amata Coleman Radewagen",
    chamber: "House",
    party: "Republican",
    state: "AS",
    district: "At-Large",
    officialHandle: "RepAmata",
  },
]
