export const VENEZUELA_KEYWORDS = [
  // Core terms
  "Maduro",
  "Venezuela",
  "Venezuelan",
  "Caribbean",
  "Trinidad",
  "USS",
  "Gerald Ford",
  "Southern Spear",
  "#OpSouthernSpear",
  "OpSouthernSpear",
  "Op Southern Spear",
  "Operation Southern Spear",
  "Trinidad & Tobago",
  "Colombia",
  "Narcotrafficking",
  "Narco",
  "Foreign Terrorist Organization",
  "Cartel of the Suns",
  "Narcoterrorism",
  "Illicit drug transit",
  "Caribbean maritime interdiction",
  "Covert operations",
  "Regime change",
  "U.S. Southern Command",
  "Freedom of navigation",
  "Drug boats",
  "Drugs",
  "Boats",
  "MCM",
  "Strike",
  "Strikes",
  "Military strike",
  "Air strike",
  "Naval strike",
  // Spanish terms
  "Designación de organización terrorista",
  "Narcotráfico de Estado",
  "Operaciones encubiertas",
  "Cambio de régimen",
  "Sanciones secundarias",
  "Licencias petroleras",
  "Despliegue naval estadounidense",
  "Contrabando",
  "Corredor antidrogas",
  "Congelamiento de activos venezolanos",
  "Procesamiento de liderazgo",
  "Decomiso de activos",
  "Intercambio de presos políticos",
  "Sanciones por derechos humanos",
  "Comando Sur",
  "Botes de droga",
  "Estados Unidos",
  "Ataque",
  "Ataques",
  "Golpe militar",
  // People and places
  "Nobel Prize",
  "Maria Corina Machado",
  "Brazil",
  "Brasil",
  "Guyana",
  "Suriname",
  "Barbados",
  "President of Venezuela",
  "President of Colombia",
  "President of Brazil",
  "President of Guyana",
  "President of Suriname",
  "USS Gerald R. Ford",
  "Gerald R. Ford",
  "CVN 78",
  "CVN-78",
  "USS Gravely",
  "USS Jason Dunham",
  "USS Sampson",
  "USS Iwo Jima",
  "USS San Antonio",
  "USS Fort Lauderdale",
  "USS Lake Erie",
  "USS Minneapolis-Saint Paul",
  "USS Newport News",
  "USS Stockdale",
  "USS Winston S. Churchill",
  "USS Bainbridge",
  "USS Mahan",
  "USS Forrest Sherman",
  "USS Mitscher",
  "MV Ocean Trader",
  // Additional context
  "SOUTHCOM",
  "Caracas",
  "Bolivarian",
  "Chavez",
  "PDVSA",
  "Citgo",
  "Venezuelan TPS",
  "Venezuelan asylum",
  "Venezuelan migrants",
  "Venezuelan refugees",
  "Boat Strikes",
  "Negotiations",
  "Delcy Rodriguez",
  "Jorge Rodriguez",
  "Venezuela sanctions",
  "Maduro sanctions",
  "Humanitarian Crisis",
  "Political Prisoners",
  "President elect Edmundo",
  "Edmundo González",
  "Tren de Aragua",
  "TDA",
  "Diosdado Cabello",
  "Nicolas Maduro",
  "Cartel de los Soles",
  "Nobel",
]

export const KEYWORD_REGEX = new RegExp(
  VENEZUELA_KEYWORDS.map((k) => `\\b${k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`).join("|"),
  "i",
)

export const REFERENCE_TEXT = `Venezuela Maduro Caribbean Trinidad USS Gerald Ford Southern Spear OpSouthernSpear Operation Southern Spear Trinidad & Tobago Colombia Narcotrafficking Narco Foreign Terrorist Organization Cartel of the Suns Narcoterrorism Illicit drug transit Caribbean maritime interdiction Covert operations Regime change U.S. Southern Command SOUTHCOM Caracas Bolivarian Chavez PDVSA Citgo Venezuelan TPS Boat Strikes Strike Strikes Military strike Air strike Naval strike Delcy Rodriguez Jorge Rodriguez Edmundo Cartel de los Soles Tren de Aragua TDA Nobel Prize Maria Corina Machado Brazil Brasil Guyana Suriname President of Venezuela Designación de organización terrorista Narcotráfico de Estado Operaciones encubiertas Cambio de régimen Despliegue naval estadounidense Contrabando Corredor antidrogas Comando Sur Ataque Ataques`

export const RELEVANCE_THRESHOLD = 0.35
